@startuml
package api
{
    package models
    {
        interface Response
        {
            +toJSON(): object
        }
        class Result
        {
            +<<readonly>>state: ResultState
            +<<readonly>>message: string
            +<<readonly>>data: Response
            +{static}Success(response: Response): Result
            +{static}Failed(message: string): Result
        }
        enum ResultState
        {
            SUCCESS,
            FAILED
        }
    }
    package routes
    {
        package " models"
        {
            class " Room"
            class RoomEntry
            class RoomExit
            class User
        }
        interface Endpoint
        {
            +path: string
            +execute(query: {[key: string]: any}, postdata?: {[key: string]: any}): Result
        }
        interface Get
        {
            +execute(query: {[key: string]: any}): Result
        }
        interface Post
        {
            +execute(query: {[key: string]: any}, postdata: {[key: string]: any}): Result
        }
        class Route
        {
            -{static}<<readonly>>_routes: Endpoint[]
            +{static}get(path: string): Endpoint
        }
    }
}
package controllers
{
    class MembersList
    {
        +{static}<<readonly>>CACHE: MembersCache
        +findByID(id: string): Member
        +indexOF(id: string): number
        +updateOfDiscord(newData: Discord): void
        +register(member: Member): void
        +isRegistedByID(id: string): boolean
    }
    class RoomAccessLogger
    {
        +{static}log(context: AccessInfo): void
    }
}
package "models "
{
    class AccessInfo
    {
        +<<readonly>>room: RoomInfo
        +<<readonly>>member: Member
        +<<readonly>>type: AccessType
        +<<readonly>>time: Date
    }
    enum AccessType
    {
        ENTRY,
        EXIT
    }
    class Discord
    {
        +<<readonly>>id: string
        +<<readonly>>nickname: string
    }
    class Game
    {
        +<<readonly>>title: string
        +<<readonly>>id: string
    }
    class Member
    {
        +<<readonly>>id: number
        +<<readonly>>name: string
        +<<readonly>>discord: Discord
        +<<readonly>>games: Game[]
    }
    class Room
    {
        +{static}<<readonly>>CACHE: RoomCache
        +<<readonly>>info: RoomInfo
        +<<readonly>>inmates: Member[]
        +{static}fromCacheOrDefault(info: RoomInfo): Room
        +entry(member: Member): void
        +exit(member: Member): void
    }
    class RoomInfo
    {
        +<<readonly>>campus: string
        +<<readonly>>name: string
    }
}
package utils
{
    package cached
    {
        abstract Cache<T extends Cacheable<any>>
        {
            #<<readonly>>_sheetID: string
            +<<readonly>>key: string
            #{abstract}fromSpreadsheet(spreadsheet: GoogleAppsScript.Spreadsheet.Spreadsheet): T[]
            #{abstract}toInstances(cached: object[]): T[]
            +get(): T[]
            +make(): T[]
        }
        interface Cacheable<T>
        {
            +fromObject(obj: object): Cacheable<T>
            +toJSON(): object
        }
        class MembersCache
        class RoomCache
    }
    package extensions
    {
        class Date
        {
            +{static}getDayToJapanese(): string
        }
        class String
        {
            +{static}insertAt(index: number, context: string): string
        }
    }
}

MembersCache --|> Cache
RoomCache --|> Cache
Endpoint --|> Get
Endpoint --|> Post

Member .up.|> Response
Member .up.|> Cacheable
Room .up.|> Response
Room .up.|> Cacheable
" Room" .up.|> Get
RoomEntry .up.|> Post
RoomExit .up.|> Post
User .up.|> Get

Member "1" *-- "1" Discord
Member "1" *-- "*" Game
Room "1" *-- "1" RoomInfo
Room "1" *-- "*" Member
Result "1" *-- "1" Response
Route "1" *-- "*" Endpoint

MembersList *--> MembersCache
Room *--> RoomCache

Cache --> Cacheable
MembersCache --> Member
AccessInfo --> Date
MembersList --> Member
Room --> String
RoomAccessLogger --> AccessInfo
Endpoint --> Result

@enduml